// <auto-generated />
namespace WPF_EF_SQLite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddAxis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAxis));
        
        string IMigrationMetadata.Id
        {
            get { return "202012021611082_AddAxis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
